spring:
  application:
    name: store
  jwt:
    secret: ${JWM_SECRET}
    accessTokenExpiration: 7200  #2h
    refreshTokenExpiration: 604800 #7d
  profiles:
      active: dev
stripe:
    secretKey: ${STIPE_SECRET_KEY}
    webhookSecretKey: ${WEBHOOK_SECRET_KEY}