spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWM_SECRET}
    accessTokenExpiration: 72000  #2h
    refreshTokenExpiration: 604800 #7d
