spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242
